name: Automated Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Test across Node versions

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Backend Testing
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend unit tests
        working-directory: backend
        run: npm test
        env:
          NODE_ENV: test
          DB_URL: ${{ secrets.TEST_DB_URL }}  # For database tests

      - name: Run backend integration tests
        working-directory: backend
        run: npm run test:integration  # Optional
        if: success()  # Only run if unit tests pass

      # Frontend Testing
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm test
        env:
          CI: true  # Essential for frontend test runners

      # Test Coverage Reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: coverage-reports-node-${{ matrix.node-version }}
          path: |
            backend/coverage
            frontend/coverage
